# -*- coding: utf-8 -*-
"""Python: Leap Year.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xcQps80lKUcJlI5D7n9V_GshXzeGhT-e

Python leap year
"""

def is_leap(year):
    leap = False
    
    # Write your logic here
    if(year%4==0):
        if(year%100==0 and year&400==0):
            leap = True
        

    return leap

year = int(input())
print(is_leap(year))