# -*- coding: utf-8 -*-
"""Second Largest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1viMfkikQiOi9JFf6JBgsc9_-cOvSq0-O

Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given  scores. Store them in a list and find the score of the runner-up.

Input Format

The first line contains . The second line contains an array   of  integers each separated by a space.

Constraints

Output Format

Print the runner-up score.

Sample Input 0

5
2 3 6 6 5
Sample Output 0

5
Explanation 0

Given list is . The maximum score is , second maximum is . Hence, we print  as the runner-up score.
"""

if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    
    
    
a=set(arr)
a.remove(max(a))
print(max(a))